version: '3'

services:
  client:
    build: src/client
    image: ubuntu:22.04
    container_name: client
    networks:
      - my_network
    volumes:
      - /Users/moabid/Downloads/CVE/CVE-2023-38408/lab/shared:/data
    depends_on:
      - server

  server:
    build: src/server
    image: ubuntu:22.04
    container_name: server
    networks:
      - my_network
    expose:
      - 22
    volumes:
      - /Users/moabid/Downloads/CVE/CVE-2023-38408/lab/shared:/data
    hostname: moabid
    healthcheck:
        test: ["CMD", "bash", "./server/entrypoint.sh"]
        interval: 30s
        timeout: 10s
        retries: 3

networks:
  my_network:
    driver: bridge